### ISSUE TITLE
Last Commit 2 Years Ago

### ISSUE THREAD

**Issue by ProfessorManhattan** [kushaldas/qubes_ansible#25]
Hey, first off, thanks for pioneering Qubes development. IMO, it should be much more widely used.

Is this project still active? I'm seeing the last commits were 2 years ago. I'm wondering if it's worth experimenting with this.

**Comment by kushaldas** [comment]
Sorry for missing the notifications, I resumed the testing today on 4.1, will update soon to make sure everything is work.

I personally use this, means I will keep developing :)

**Comment by kushaldas** [comment]
Closing this as we are fully back into updating.
